### ISSUE TITLE
$destroy event missing

### ISSUE THREAD

**Issue by tcederquist** [kjartanvalur/angular-kendo-window#22]
A great library! Thanks for assembling this code.

A few items I've found using this in my single page app which is resource leak sensitive. Not able to figure out how to fix it as this is beyond my angular skill level. If you register an $on event listener in the controlleras, it's never given an opportunity as $destroy is never called and the controllers seems to persist for the life of the page even after the window is closed (perhaps the $on is holding it in memory?). Using the 'x' on the window. Two potential issues from this:
1) Resource leak with extra 'on' listeners never go away
2) controller stack just grows for each window. I have a large single page app and this is a challenge
3) $windowInstance does not have an id in it. Even the plunker example isn't populating the id.

One of the close methods is called when this occurs so it sees it, just not sure how to get that message all the way through to the controller.

Would also be nice to have the ability to hook into events like resize (which is how I discovered this). Currently I have to hook the kendo resize and then rootscope broadcast and have the target controlleras look for messages with $scope.$id within one as the filter, kendo.window seems to create two controllers back to back when it starts, the one from Kendo? and the one from your injections of the controlleras as registered.

**Comment by kjartanvalur** [comment]
Hi sorry for late response!! Been really busy and to be honest I do not have many extra time to spend on this project, since most of my projects are now angular2. If you are interested in helping out then we need all the help we can get.

These are all valid points, but you can hook up any kendo event in the options object like so
http://plnkr.co/edit/j6K0gNeTTHvnhf5rQax5?p=preview
