### ISSUE TITLE
close event does not seem to have any argumments

### ISSUE THREAD

**Issue by pateketu** [kjartanvalur/angular-kendo-window#32]
Hello, 

I am trying to capture the close event and prevent window from closing based on some validation rule, following plunker shows http://plnkr.co/edit/EacLulnJbMqUffufjmgn?p=preview that the close event has got the "event" argument but latest version of kWindow that I have does not seem to have any arguments in close event?

Thanks
Ketul

**Comment by kjartanvalur** [comment]
This is a limitation to the close event because that is a kendo event. But I suggest you do your validation in the dialog where you have a save and cancel button events. But the limitation then is when the user clickes the x button in the top-right corner... But there are ways to deal with that e.g. rootscope dirty flag.

**Comment by pateketu** [comment]
I ended up doing validation on the save button in the dialog, did not need to trigger validation on cancel or X button!

**Comment by kjartanvalur** [comment]
Fixed
